const ActionTypes = {
    SIGNUP_USER : 'SIGNUP_USER',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILED:'SIGNUP_FAILED',

    LOGIN_USER : 'LOGIN_USER',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',

    CHATING_REQUEST :' CHATING_REQUEST',
    CHATING_REQUEST_FAILED :' CHATING_REQUEST_FAILED',
    CHATING_REQUEST_SUCCESS :'CHATING_REQUEST_SUCCESS',
    DISPATCH_CHATING_REQUEST :' DISPATCH_CHATING_REQUEST',
    DISPATCH_CHATING_REQUEST_FAILED :' DISPATCH_CHATING_REQUEST_FAILED',
    DISPATCH_CHATING_REQUEST_SUCCESS :'DISPATCH_CHATING_REQUEST_SUCCESS'


}

export default ActionTypes;
