const ActionTypes = {
    SIGNUP_USER : 'SIGNUP_USER',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILED:'SIGNUP_FAILED',

    LOGIN_USER : 'LOGIN_USER',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',

    CHATING_REQUEST :' CHATING_REQUEST',
    CHATING_REQUEST_FAILED :' CHATING_REQUEST_FAILED',
    CHATING_REQUEST_SUCCESS :'CHATING_REQUEST_SUCCESS',

    DISPATCH_CHATING_REQUEST :' DISPATCH_CHATING_REQUEST',
    DISPATCH_CHATING_REQUEST_FAILED :' DISPATCH_CHATING_REQUEST_FAILED',
    DISPATCH_CHATING_REQUEST_SUCCESS :'DISPATCH_CHATING_REQUEST_SUCCESS',

    
    CHAT_REQUEST :' CHAT_REQUEST',
    CHAT_REQUEST_FAILED :' CHAT_REQUEST_FAILED',
    CHAT_REQUEST_SUCCESS :'CHAT_REQUEST_SUCCESS',
    DISPATCH_RECIEVER_CHATING_REQUEST_SUCCESS:'DISPATCH_RECIEVER_CHATING_REQUEST_SUCCESS',

    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_REQUEST_SUCCESS:'LOGOUT_REQUEST_SUCCESS',
    LOGOUT_REQUEST_FAILED : 'LOGOUT_REQUEST_FAILED',

FB_LOGIN:'FB_LOGIN',
FB_LOGIN_SUCCESS : 'FB_LOGIN_SUCCESS',
FB_LOGIN_FAILED : 'FB_LOGIN_FAILED',



}

export default ActionTypes;
